name: 'Upload Module Build'
description: ''
runs:
  using: "composite"
  steps:
    # ignore Stable_Release and treat is as Release
    - name: Build MCM (Release)
      run: >-
        mkdir bannerlord-publish;
        dotnet build src/MCM.NexusMods/MCM.NexusMods.csproj --configuration Stable_Release -p:GameFolder="$PWD/bannerlord-publish";
        dotnet build src/MCM.Implementation.MCMv3/MCM.Implementation.MCMv3.csproj --configuration Stable_Release -p:GameFolder="$PWD/bannerlord-publish";
        dotnet build src/MCM.Implementation.ModLib/MCM.Implementation.ModLib.csproj --configuration Stable_Release -p:GameFolder="$PWD/bannerlord-publish";
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh

    - name: Upload Bannerlord folder
      uses: actions/upload-artifact@v2
      with:
        name: bannerlord
        path: ./bannerlord-publish/