name: 'Download Build'
description: ''
runs:
  using: "composite"
  steps:
    - name: Download bannerlord folder
      uses: actions/download-artifact@v2
      with:
        name: bannerlord
        path: ./bannerlord

    - name: Zip MCM.Standalone
      run: 7z a -tzip MCM.Standalone.zip ./bannerlord/*
      shell: pwsh