name: Verify NexusMods Cookies

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  verify-nexusmods-cookies:
    name: Verify NexusMods Cookies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/setup

    - name: Install Bannerlord.NexusmodsUploader
      run: dotnet tool install -g Bannerlord.NexusmodsUploader
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh

    - name: Start Selenoid
      uses: Xotabu4/selenoid-github-action@v1

    - name: Run NexusmodsUploader
      run: bannerlord_nexusmods_uploader verifycookies;
      env:
        NEXUSMODS_COOKIES_JSON: '${{secrets.NEXUSMODS_COOKIES_JSON}}'
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      shell: pwsh
