name: Test

on:
  repository_dispatch:
    types:
      # If a new version of the game is released, test the repo against it.
      # This way we will always know if the repo is broken on a new update.
      - game_version_update
  push:
    branches:
      - dev
      - dev-workflow-test
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'
  pull_request:
    branches:
      - dev
    # will be triggereg when undrafting or requesting review
    types: [review_requested, ready_for_review]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/setup
    - uses: ./.github/actions/download-game-binaries
    - uses: ./.github/actions/test-and-upload-report
