name: Test and Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Test and Build
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/setup
    - uses: ./.github/actions/download-game-binaries
    - uses: ./.github/actions/test-and-upload-report
    - uses: ./.github/actions/upload-build

###########################
#        NUGET/GPR        #
###########################
  publish-on-nuget:
    name: Publish on NuGet
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/setup
    - uses: ./.github/actions/package-release

###########################
#          NEXUS          #
###########################
  publish-on-nexusmods:
    if: ${{ false }}
    name: Publish on NexusMods
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/setup
    - uses: ./.github/actions/download-build
    - uses: ./.github/actions/nexusmods-release

###########################
#         GITHUB          #
###########################
  publish-on-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/setup
    - uses: ./.github/actions/download-build
    - uses: ./.github/actions/github-release
